apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: splattop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: SplatTop production project (default + monitoring namespaces)

  sourceRepos:
    - https://github.com/cesaregarza/SplatTopConfig

  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: cert-manager.io
      kind: Certificate
    - group: cert-manager.io
      kind: ClusterIssuer

  namespaceResourceWhitelist:
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: cilium.io
      kind: CiliumNetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: cert-manager.io
      kind: Certificate

  orphanedResources:
    warn: true
    ignore:
      - group: ''
        kind: Secret
        name: regcred
      - group: ''
        kind: Secret
        name: db-secrets
      - group: ''
        kind: Secret
        name: grafana-admin-credentials
      - group: ''
        kind: Secret
        name: alertmanager-config
      - group: ''
        kind: Secret
        name: tls-secret
      - group: ''
        kind: Secret
        name: grafana-tls
      - group: ''
        kind: ConfigMap
        name: kube-root-ca.crt

  syncWindows:
    - kind: allow
      schedule: '0 15 * * 1-5'
      duration: 11h
      applications:
        - '*'
      clusters:
        - '*'
      namespaces:
        - '*'

  roles:
    - name: admin
      description: Admin access scoped to SplatTop production
      policies:
        - p, proj:splattop:admin, applications, *, splattop/*, allow
      groups:
        - splattop-admins
